### Get all buildings
GET http://localhost:3000/api/buildings
X-API-Key: KEY
Accept: application/json

### Get new building
POST http://localhost:3000/api/buildings
Accept: application/json
X-API-Key: KEY
Content-Type: application/json

{
  "code": "B",
  "name": "ITEBA"
}

### Get building by Id
GET http://localhost:3000/api/buildings/1
X-API-Key: KEY
Accept: application/json

### Update building
PUT http://localhost:3000/api/buildings/2
X-API-Key: KEY
Accept: application/json
Content-Type: application/json

{
  "code": "B",
  "name": "Gedung ITEBA"
}

### Delete building
DELETE http://localhost:3000/api/buildings/3
X-API-Key: KEY
Accept: application/json